"use server";
// seed.ts

import { db } from "@/lib/db";

const brands = [
  {
    name: "Abarth",
    models: [
      "124 Spider",
      "500",
      "500C",
      "595",
      "595 Competizione",
      "695",
      "695C",
      "Grande Punto",
      "Punto Evo",
    ],
  },
  {
    name: "Acura",
    models: ["MDX", "NSX", "RL", "RSX", "TL", "TSX"],
  },
  {
    name: "Aiways",
    models: ["U5"],
  },
  {
    name: "Aixam",
    models: ["City", "Crossline", "Roadline", "Scouty R"],
  },
  {
    name: "Alfa Romeo",
    models: [
      "4C",
      "8C",
      "Alfa 145",
      "Alfa 146",
      "Alfa 147",
      "Alfa 155",
      "Alfa 156",
      "Alfa 159",
      "Alfa 164",
      "Alfa 166",
      "Alfa 33",
      "Alfa 75",
      "Alfa 90",
      "Alfasud",
      "Alfetta",
      "Brera",
      "Crosswagon",
      "Giulia",
      "Giulietta",
      "GT",
      "GTV",
      "Junior",
      "MiTo",
      "Spider",
      "Sprint",
      "Stelvio",
      "Tonal",
    ],
  },
  {
    name: "ALPINA",
    models: [
      "B10",
      "B12",
      "B3",
      "B4",
      "B5",
      "B6",
      "B7",
      "B8",
      "D10",
      "D3",
      "D4",
      "D5",
      "Roadster S",
      "XB7",
      "XD3",
      "XD4",
    ],
  },
  {
    name: "Alpine",
    models: ["A110"],
  },
  {
    name: "Ariel",
    models: ["Atom"],
  },
  {
    name: "Artega",
    models: ["GT"],
  },
  {
    name: "Asia Motors",
    models: ["Rocsta"],
  },
  {
    name: "Aston Martin",
    models: [
      "AR1",
      "Cygnet",
      "DB",
      "DB11",
      "DB12",
      "DB7",
      "DB9",
      "DBS",
      "DBX",
      "Lagonda",
      "Rapide",
      "V12 Vantage",
      "V8 Vantage",
      "Vanquish",
      "Virage",
    ],
  },
  {
    name: "Audi",
    models: [
      "100",
      "200",
      "80",
      "90",
      "A1",
      "A2",
      "A3",
      "A4",
      "A4 Allroad",
      "A5",
      "A6",
      "A6 Allroad",
      "A7",
      "A8",
      "Cabriolet",
      "Coupé",
      "e-tron",
      "e-tron GT",
      "Q1",
      "Q2",
      "Q3",
      "Q4",
      "Q4 e-tron",
      "Q5",
      "Q6 e-tron",
      "Q7",
      "Q8",
      "quattro",
      "R8",
      "RS2",
      "RS3",
      "RS4",
      "RS5",
      "RS6",
      "RS7",
      "RS e-tron GT",
      "RSQ3",
      "RSQ8",
      "S1",
      "S2",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "SQ2",
      "SQ5",
      "SQ6 e-tron",
      "SQ7",
      "SQ8",
      "TT",
      "TT RS",
      "TTS",
      "V8",
    ],
  },
  {
    name: "BAIC",
    models: [
      "BJ20",
      "BJ40",
      "Senova D20",
      "Senova x25",
      "Senova x35",
      "Senova x55",
      "Senova x65",
      "X55",
      "X75",
    ],
  },
  {
    name: "Bentley",
    models: [
      "Arnage",
      "Azure",
      "Bentayga",
      "Brooklands",
      "Continental",
      "Continental Flying Spur",
      "Continental GT",
      "Continental GTC",
      "Continental Supersports",
      "Eight",
      "Flying Spur",
      "Mulsanne",
      "S2",
      "Turbo R",
      "Turbo RT",
      "Turbo S",
    ],
  },
  {
    name: "BMW",
    models: [
      // 1 Series
      "114",
      "116",
      "118",
      "120",
      "123",
      "125",
      "128",
      "130",
      "135",
      // 2 Series
      "214",
      "216",
      "218",
      "220",
      "225",
      "228",
      "230",
      "235",
      "240",
      // 3 Series
      "315",
      "316",
      "318",
      "320",
      "323",
      "325",
      "328",
      "330",
      "335",
      "340",
      // 4 Series
      "418",
      "420",
      "425",
      "428",
      "430",
      "435",
      "440",
      // 5 Series
      "518",
      "520",
      "523",
      "525",
      "528",
      "530",
      "535",
      "540",
      "545",
      "550",
      // 6 Series
      "628",
      "630",
      "633",
      "635",
      "640",
      "645",
      "650",
      // 7 Series
      "725",
      "728",
      "730",
      "732",
      "735",
      "740",
      "745",
      "750",
      "760",
      // 8 Series
      "830",
      "840",
      "850",
      // i Series (Electric)
      "i3",
      "i4",
      "i5",
      "i7",
      "i8",
      // X Series (SUV/Crossover)
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "X8",
      // Z Series (Roadsters)
      "Z1",
      "Z3",
      "Z4",
      "Z8",
      // M Series (Performance)
      "M1",
      "M2",
      "M3",
      "M4",
      "M5",
      "M6",
      "M8",
      // X M Series (Performance SUV/Crossover)
      "X1 M",
      "X2 M",
      "X3 M",
      "X4 M",
      "X5 M",
      "X6 M",
      // Z M Series
      "Z4 M",
    ],
  },
  {
    name: "Brilliance",
    models: ["BC3", "BS2", "BS4", "BS6"],
  },
  {
    name: "Bugatti",
    models: ["Chiron", "EB 110", "Veyron"],
  },
  {
    name: "Buick",
    models: [
      "Century",
      "Electra",
      "Enclave",
      "La Crosse",
      "Le Sabre",
      "Park Avenue",
      "Regal",
      "Riviera",
      "Roadmaster",
      "Skylark",
    ],
  },
  {
    name: "BYD",
    models: ["ATTO3", "DOLPHIN", "HAN", "SEAL", "TANG"],
  },
  {
    name: "Cadillac",
    models: [
      "Allante",
      "ATS",
      "BLS",
      "CT6",
      "CTS",
      "Deville",
      "Eldorado",
      "Escalade",
      "Fleetwood",
      "Seville",
      "SRX",
      "STS",
      "XLR",
      "XT4",
      "XT5",
      "XT6",
    ],
  },
  {
    name: "Chevrolet",
    models: [
      "2500",
      "Alero",
      "Astro",
      "Avalanche",
      "Aveo",
      "Beretta",
      "Blazer",
      "C1500",
      "Camaro",
      "Caprice",
      "Captiva",
      "Cavalier",
      "Chevelle",
      "Chevy Van",
      "Citation",
      "Colorado",
      "Corsica",
      "Cruze",
      "El Camino",
      "Epica",
      "Evanda",
      "Express",
      "G",
      "HHR",
      "Impala",
      "K1500",
      "K30",
      "Kalos",
      "Lacetti",
      "Lumina",
      "Malibu",
      "Matiz",
      "Niva",
      "Nubira",
      "Orlando",
      "Rezzo",
      "S-10",
      "Silverado",
      "Spark",
      "SSR",
      "Suburban",
      "Tahoe",
      "Trailblazer",
      "Trans Sport",
      "Traverse",
      "Trax",
      "Venture",
      "Volt",
    ],
  },
  {
    name: "Chrysler",
    models: [
      "200",
      "300C",
      "300M",
      "Aspen",
      "Crossfire",
      "Daytona",
      "ES",
      "Grand Voyager",
      "GS",
      "GTS",
      "Imperial",
      "Le Baron",
      "Neon",
      "New Yorker",
      "Pacifica",
      "PT Cruiser",
      "Saratoga",
      "Sebring",
      "Stratus",
      "Valiant",
      "Viper",
      "Vision",
      "Voyager",
    ],
  },
  {
    name: "Citroen",
    models: [
      "2 CV",
      "AX",
      "Berlingo",
      "BX",
      "C1",
      "C2",
      "C3",
      "C3 Aircross",
      "C3 Picasso",
      "C4",
      "C4 Aircross",
      "C4 Picasso",
      "C4 Cactus",
      "C4 SpaceTourer",
      "C4 X",
      "C5",
      "C5 Aircross",
      "C5 X",
      "C6",
      "C8",
      "C-Crosser",
      "C-Elysée",
      "CX",
      "C-Zero",
      "DS",
      "DS3",
      "DS4",
      "DS4 Crossback",
      "DS5",
      "E-MEHARI",
      "Evasion",
      "Grand C4 Picasso / SpaceTourer",
      "GSA",
      "Jumper",
      "Jumpy",
      "Nemo",
      "SAXO",
      "SM",
      "SpaceTourer",
      "Visas",
      "Xantia",
      "XM",
      "Xsara",
      "Xsara Picasso",
      "ZX",
    ],
  },
  {
    name: "Corvette",
    models: ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "Z06", "ZR1"],
  },
  {
    name: "Cupra",
    models: ["Arona", "Ateca", "Born", "Formgate", "Ibiza", "Leon"],
  },
  {
    name: "Dacia",
    models: [
      "Dokker",
      "Duster",
      "Jogger",
      "Lodgy",
      "Logan",
      "Sandero",
      "Spring",
    ],
  },
  {
    name: "Daewoo",
    models: [
      "Espero",
      "Evanda",
      "Kalos",
      "Korando",
      "Lacetti",
      "Lanos",
      "Leganza",
      "Matiz",
      "Musso",
      "Nexia",
      "Nubira",
      "Rezzo",
      "Tacuma",
    ],
  },
  {
    name: "Daihatsu",
    models: [
      "Applause",
      "Charade",
      "Charmant",
      "Copen",
      "Cuore",
      "Feroza/Sportrak",
      "Freeclimber",
      "Gran Move",
      "Hijet",
      "Materia",
      "Move",
      "Rocky/Fourtrak",
      "Sirion",
      "Terios",
      "Trevis",
      "YRV",
    ],
  },
  {
    name: "DeTomaso",
    models: ["Guara", "Pantera"],
  },
  {
    name: "DFSK",
    models: [
      "EC31",
      "EC35",
      "Fengon",
      "Fengon 5",
      "Fengon 500",
      "Fengon 600",
      "Fengon 7",
      "Forthing 4",
      "Forthing 5",
      "Glory",
      "K01",
      "Seres 3",
      "Seres 5",
    ],
  },
  {
    name: "Dodge",
    models: [
      "Avenger",
      "Caliber",
      "Challenger",
      "Charger",
      "Coronet",
      "Dakota",
      "Dart",
      "Demon",
      "Durango",
      "Grand Caravan",
      "Hornet",
      "Journey",
      "Magnum",
      "Neon",
      "Nitro",
      "RAM",
      "Stealth",
      "Viper",
    ],
  },
  {
    name: "Donkervoort",
    models: ["D8", "S7", "S8"],
  },
  {
    name: "DS Automobiles",
    models: [
      "DS3",
      "DS3 Crossback",
      "DS4",
      "DS4 Crossback",
      "DS5",
      "DS7",
      "DS9",
    ],
  },
  {
    name: "e.GO",
    models: ["Life"],
  },
  {
    name: "Ferrari",
    models: [
      "208",
      "246",
      "250",
      "275",
      "288",
      "296 GTB",
      "296 GTS",
      "308",
      "328",
      "330",
      "348",
      "360",
      "365",
      "400",
      "412",
      "456",
      "458",
      "488 GTB",
      "488 Pista",
      "488 Spider",
      "512",
      "550",
      "575",
      "599 GTB",
      "599 GTO",
      "599 SA Aperta",
      "612",
      "750",
      "812",
      "California",
      "Dino GT4",
      "Enzo Ferrari",
      "F12",
      "F355",
      "F40",
      "F430",
      "F50",
      "F8",
      "FF",
      "GTC4Lusso",
      "LaFerrari",
      "Mondial",
      "Portofino",
      "Purosanque",
      "Roma",
      "SF90",
      "Superamerica",
      "Testarossa",
    ],
  },
  {
    name: "Fiat",
    models: [
      "124",
      "124 Spider",
      "126",
      "127",
      "130",
      "131",
      "500",
      "500C",
      "500e",
      "500L",
      "500X",
      "600",
      "600e",
      "Albea",
      "Barchetta",
      "Brava",
      "Bravo",
      "Cinquecento",
      "Coupe",
      "Croma",
      "Dino",
      "Doblo",
      "Ducato",
      "Fiorino",
      "Freemont",
      "Fullback",
      "Grande Punto",
      "Idea",
      "Linea",
      "Marea",
      "Marengo",
      "Multipla",
      "New Panda",
      "Palio",
      "Panda",
      "Punto",
      "Punto Evo",
      "Qubo",
      "Regata",
      "Ritmo",
      "Scudo",
      "Sedici",
      "Seicento",
      "Siena",
      "Spider Europe",
      "Stilo",
      "Strada",
      "Talento",
      "Tempra",
      "Tipo",
      "Ulysse",
      "Uno",
      "X 1/9",
    ],
  },
  {
    name: "Fisker",
    models: ["Karma", "Ocean"],
  },
  {
    name: "Ford",
    models: [
      "Aerostar",
      "B-Max",
      "Bronco",
      "Bronco Sport",
      "Capri",
      "C-Max",
      "Cougar",
      "Courier",
      "Crown",
      "Econoline",
      "Econovan",
      "EcoSport",
      "Edge",
      "Escape",
      "Escort",
      "Excursion",
      "Expedition",
      "Express",
      "F100",
      "F150",
      "F250",
      "F350",
      "Fairlane",
      "Falcon",
      "Fiesta",
      "Flex",
      "Focus",
      "Fusion",
      "Galaxy",
      "Granada",
      "Grand C-Max",
      "Grand Tourneo",
      "GT",
      "Ka",
      "Ka+",
      "Kuga",
      "Maverick",
      "Mondeo",
      "Mustang",
      "Mustang Mach-e",
      "Orion",
      "Puma",
      "Ranger",
      "Raptor",
      "Scorpio",
      "Sierra",
      "S-Max",
      "Sportka",
      "Streetka",
      "Taunus",
      "Taurus",
      "Thunderbird",
      "Tourneo",
      "Transit",
      "Windstar",
    ],
  },
  {
    name: "Genesis",
    models: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  },
  {
    name: "GMC",
    models: [
      "Acadia",
      "Envoy",
      "Safari",
      "Savana",
      "Sierra",
      "Sonoma",
      "Syclone",
      "Terrain",
      "Typhoon",
      "Vandura",
      "Yukon",
    ],
  },
  {
    name: "Grecav",
    models: ["Sonique"],
  },
  {
    name: "GWM",
    models: ["Ora 03", "Ora 07", "Wey 03", "Wey 05"],
  },
  {
    name: "Honda",
    models: [
      "Accord",
      "Aerodeck",
      "City",
      "Civic",
      "Clarity",
      "Concerto",
      "CR-V",
      "CRX",
      "CR-Z",
      "e",
      "e:Ny1",
      "Element",
      "FR-V",
      "HR-V",
      "Insight",
      "Integra",
      "Jazz",
      "Legend",
      "Logo",
      "NSX",
      "Odyssey",
      "Pilot",
      "Prelude",
      "Ridgeline",
      "S2000",
      "Shuttle",
      "Stream",
      "ZR-V",
    ],
  },
  {
    name: "Hummer",
    models: ["H1", "H2", "H3"],
  },
  {
    name: "Hyundai",
    models: [
      "Accent",
      "Atos",
      "Azera",
      "Bayon",
      "Coupe",
      "Elantra",
      "Excel",
      "Galloper",
      "Genesis",
      "Getz",
      "Grandeur",
      "Grand Santa Fe",
      "H-1",
      "H100",
      "H200",
      "H350",
      "i10",
      "i20",
      "i30",
      "i40",
      "IONIQ",
      "IONIQ 5",
      "IONIQ 6",
      "ix20",
      "ix35",
      "ix55",
      "Kona",
      "Lantra",
      "Matrix",
      "Nexo",
      "Pony",
      "Santa Fe",
      "Santamo",
      "Sonata",
      "Staria",
      "Terracan",
      "Trajet",
      "Tucson",
      "Veloster",
      "Veracruz",
      "XG30",
      "XG350",
    ],
  },
  {
    name: "INEOS",
    models: ["Grenadier"],
  },
  {
    name: "Infiniti",
    models: [
      "EX30",
      "EX35",
      "EX37",
      "FX",
      "G35",
      "G37",
      "M30",
      "M35",
      "M37",
      "Q30",
      "Q45",
      "Q50",
      "Q60",
      "Q70",
      "QX30",
      "QX50",
      "QX56",
      "QX60",
      "QX70",
      "QX80",
    ],
  },
  {
    name: "Isuzu",
    models: ["Campo", "D-Max", "Gemini", "Midi", "PICK UP", "Trooper"],
  },
  {
    name: "Iveco",
    models: ["Massif"],
  },
  {
    name: "JAC",
    models: ["T8"],
  },
  {
    name: "Jaguar",
    models: [
      "Daimler",
      "E-Pace",
      "E-Type",
      "F-Pace",
      "F-Type",
      "I-Pace",
      "Mk II",
      "S-Type",
      "XE",
      "XF",
      "XJ",
      "XJ12",
      "XJ40",
      "XJ6",
      "XJ8",
      "XJR",
      "XJS",
      "XJSC",
      "XK",
      "XK8",
      "XKR",
      "X-Type",
    ],
  },
  {
    name: "Jeep",
    models: [
      "Avenger",
      "Cherokee",
      "Cj",
      "Comanche",
      "Commander",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Patriot",
      "Renegade",
      "Wagoneer",
      "Willys",
      "Wrangler",
    ],
  },
  {
    name: "Kia",
    models: [
      "Besta",
      "Borrego",
      "Carens",
      "Carnival",
      "Ceed",
      "Ceed Sportswagon",
      "Cerato",
      "Clarus",
      "Elan",
      "EV6",
      "EV9",
      "Joice",
      "K2500",
      "K2700",
      "Leo",
      "Magentis",
      "Mentor",
      "Mini",
      "Niro",
      "Opirus",
      "Optima",
      "Picanto",
      "Pregio",
      "Pride",
      "ProCeed",
      "Retona",
      "Rio",
      "Roadster",
      "Rocsta",
      "Sephia",
      "Shuma",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
      "Stonic",
      "Venga",
      "XCeed",
    ],
  },
  {
    name: "Koenigsegg",
    models: ["Agera", "CCR", "CCXR"],
  },
  {
    name: "KTM",
    models: ["X-BOW"],
  },
  {
    name: "Lada",
    models: [
      "110",
      "111",
      "112",
      "1200",
      "2107",
      "2110",
      "2111",
      "2112",
      "Aleko",
      "Forma",
      "Granta",
      "Kalina",
      "Niva",
      "Nova",
      "Priora",
      "Samara",
      "Taiga",
      "Urban",
      "Vesta",
      "X-ray",
    ],
  },
  {
    name: "Lamborghini",
    models: [
      "Aventador",
      "Countach",
      "Diablo",
      "Espada",
      "Gallardo",
      "Huracan",
      "Jalpa",
      "LM",
      "Miura",
      "Murcielago",
      "Urraco",
      "Urus",
    ],
  },
  {
    name: "Lancia",
    models: [
      "Beta",
      "Dedra",
      "Delta",
      "Flaminia",
      "Flavia",
      "Fulvia",
      "Gamma",
      "Kappa",
      "Lybra",
      "MUSA",
      "Phedra",
      "Prisma",
      "Stratos",
      "Thema",
      "Thesis",
      "Voyager",
      "Ypsilon",
      "Zeta",
    ],
  },
  {
    name: "Land Rover",
    models: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
      "Series I",
      "Series II",
      "Series III",
    ],
  },
  {
    name: "Landwind",
    models: ["CV-9", "S", "SC2", "SC4"],
  },
  {
    name: "Lexus",
    models: [
      "ES 300",
      "ES 330",
      "ES 350",
      "GS 250",
      "GS 300",
      "GS 350",
      "GS 430",
      "GS 450",
      "GS 460",
      "GS F",
      "GX 460",
      "IS 200",
      "IS 220",
      "IS 250",
      "IS 300",
      "IS 350",
      "IS-F",
      "LBX",
      "LC 500",
      "LC 500h",
      "LFA",
      "LM",
      "LS 400",
      "LS 430",
      "LS 460",
      "LS 500",
      "LS 600",
      "LX 450",
      "LX 470",
      "LX 500",
      "LX 570",
      "LX 600",
      "NX 200",
      "NX 300",
      "NX 350",
      "NX 450",
      "RC 200",
      "RC 300",
      "RC 350",
      "RC F",
      "RX 200",
      "RX 300",
      "RX 330",
      "RX 350",
      "RX 400",
      "RX 450",
      "RX 500",
      "RZ",
      "SC 400",
      "SC 430",
      "UX",
    ],
  },
  {
    name: "Ligier",
    models: [
      "Ambra",
      "Be Sun",
      "JS 50",
      "JS 50 L",
      "JS 60",
      "JS RC",
      "Myli",
      "Nova",
      "Optima",
      "X - Too",
    ],
  },
  {
    name: "Lincoln",
    models: ["Aviator", "Continental", "LS", "Mark", "Navigator", "Town Car"],
  },
  {
    name: "Lotus",
    models: [
      "340 R",
      "Cortina",
      "Elan",
      "Eletre",
      "Elise",
      "Elite",
      "Emeya",
      "Esprit",
      "Europe",
      "Evora",
      "Excel",
      "Exige",
      "Super Seven",
    ],
  },
  {
    name: "Lucid",
    models: ["Air"],
  },
  {
    name: "Lynk & Co",
    models: ["01"],
  },
  {
    name: "MAN",
    models: ["TGE"],
  },
  {
    name: "Maserati",
    models: [
      "222",
      "224",
      "228",
      "3200",
      "418",
      "420",
      "4200",
      "422",
      "424",
      "430",
      "Biturbo",
      "Ghibli",
      "GranCabrio",
      "GranSport",
      "GranTurismo",
      "Grecale",
      "Indy",
      "Karif",
      "Levante",
      "MC12",
      "MC20",
      "Merak",
      "Quattroporte",
      "Shamal",
      "Spyder",
    ],
  },
  {
    name: "Maxus",
    models: [
      "Deliver 9",
      "eDeliver 3",
      "eDeliver 9",
      "Euniq 5",
      "Euniq 6",
      "Mifa 9",
      "T90",
    ],
  },
  {
    name: "Maybach",
    models: ["57", "62", "Pullman", "S650"],
  },
  {
    name: "Mazda",
    models: [
      "121",
      "2",
      "2 Hybrid",
      "3",
      "323",
      "5",
      "6",
      "626",
      "929",
      "Bongo",
      "B Series",
      "BT-50",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-60",
      "CX-7",
      "CX-80",
      "CX-9",
      "Demio",
      "E Series",
      "Millenia",
      "MPV",
      "MX-3",
      "MX-5",
      "MX-6",
      "Premacy",
      "Protege",
      "RX-6",
      "RX-7",
      "RX-8",
      "Tribute",
      "Xedos",
    ],
  },
  {
    name: "McLaren",
    models: [
      "540C",
      "540GT",
      "570S",
      "600LT",
      "620R",
      "650S",
      "650S Coupe",
      "675LT",
      "675LT Spider",
      "720S",
      "750S",
      "765LT",
      "Artura",
      "Elva",
      "GT",
      "MP4-12C",
      "P1",
      "Senna",
      "Senna GTR",
      "Speedtail",
    ],
  },
  {
    name: "Mercedes-Benz",
    models: [
      "A-Class",
      "B-Class",
      "C-Class",
      "CL-Class",
      "CLA-Class",
      "CLC-Class",
      "CLK-Class",
      "CLS-Class",
      "E-Class",
      "G-Class",
      "GL-Class",
      "GLA-Class",
      "GLB-Class",
      "GLC-Class",
      "GLE-Class",
      "GLK-Class",
      "GLS-Class",
      "M-Class",
      "R-Class",
      "S-Class",
      "SL-Class",
      "SLC-Class",
      "SLK-Class",
      "V-Class",
      "X-Class",
      "AMG GT",
      "AMG GLA",
      "AMG GLC",
      "AMG GLE",
      "AMG GLS",
      "AMG S",
      "EQC",
      "EQA",
      "EQB",
      "EQE",
      "EQS",
      "Maybach S-Class",
    ],
  },
  {
    name: "MG",
    models: [
      "EHS",
      "HS",
      "Marvel R",
      "MG3",
      "MG4",
      "MG5",
      "MGA",
      "MGB",
      "MGF",
      "Midget",
      "Montego",
      "TD",
      "TF",
      "ZR",
      "ZS",
      "ZT",
    ],
  },
  {
    name: "Microcar",
    models: ["Dué", "Flex", "M.GO", "M-8", "MC1", "MC2", "Virgo"],
  },
  {
    name: "Microlino",
    models: ["Competizione", "Dolce", "Pioneer"],
  },
  {
    name: "Mitsubishi",
    models: [
      "3000 GT",
      "ASX",
      "Canter",
      "Carisma",
      "Colt",
      "Cordia",
      "Cosmos",
      "Diamante",
      "Eclipse",
      "Eclipse Cross",
      "Galant",
      "Grandis",
      "i-MiEV",
      "L200",
      "L300",
      "L400",
      "Lancer",
      "Mirage",
      "Outlander",
      "Pajero",
      "Pajero Pinin",
      "Pick-up",
      "Plug-in Hybrid Outlander",
      "Santamo",
      "Sapporo",
      "Sigma",
      "Space Gear",
      "Space Runner",
      "Space Star",
      "Space Wagon",
      "Starion",
      "Tredia",
    ],
  },
  {
    name: "Morgan",
    models: [
      "3 Wheeler",
      "4/4",
      "Aero 8",
      "Plus 4",
      "Plus 6",
      "Plus 8",
      "Roadster",
    ],
  },
  {
    name: "NIO",
    models: ["EL6", "EL7", "ET5", "ET7"],
  },
  {
    name: "Nissan",
    models: [
      "100 NX",
      "200 SX",
      "240SX",
      "300ZX",
      "350Z",
      "370Z",
      "Almera",
      "Almera Tino",
      "Altima",
      "Ariya",
      "Bluebird",
      "Cabstar",
      "Cargo",
      "Cherry",
      "Cube",
      "e-NV200",
      "Evalia",
      "Frontier",
      "GT-R",
      "Interstar",
      "Juke",
      "King Cab",
      "Kubistar",
      "Laurel",
      "Leaf",
      "Maxima",
      "Micra",
      "Murano",
      "Navara",
      "Note",
      "NP 300",
      "NV200",
      "NV250",
      "NV300",
      "NV400",
      "Pathfinder",
      "Patrol",
      "PickUp",
      "Pixo",
      "Prairie",
      "Primastar",
      "Primera",
      "Pulsar",
      "Qashqai",
      "Qashqai+2",
      "Quest",
      "Sentra",
      "Serena",
      "Silvia",
      "Skyline",
      "Sunny",
      "Terrano",
      "Tiida",
      "Titan",
      "Townstar",
      "Trade",
      "Urvan",
      "Vanette",
      "X-Trail",
    ],
  },
  {
    name: "Oldsmobile",
    models: [
      "Bravada",
      "Custom Cruiser",
      "Cutlass",
      "Delta 88",
      "Silhouette",
      "Supreme",
      "Toronado",
    ],
  },
  {
    name: "Opel",
    models: [
      "Adam",
      "Agila",
      "Ampera",
      "Ampera-e",
      "Antara",
      "Arena",
      "Ascona",
      "Astra",
      "Calibra",
      "Campo",
      "Cascada",
      "Cavalier",
      "Combo",
      "Combo Life",
      "Commodore",
      "Corsa",
      "Crossland",
      "Diplomat",
      "Frontera",
      "Grandland",
      "GT",
      "Insignia",
      "Insignia CT",
      "Kadett",
      "Karl",
      "Manta",
      "Meriva",
      "Mokka",
      "Mokka-e",
      "Mokka X",
      "Monterey",
      "Monza",
      "Nova",
      "Omega",
      "Pick Up Sportscap",
      "Rekord",
      "Rocks-e",
      "Senator",
      "Signum",
      "Sintra",
      "Speedster",
      "Tigra",
      "Vectra",
      "Vivaro",
      "Zafira",
      "Zafira Life",
      "Zafira Tourer",
    ],
  },
  {
    name: "ORA",
    models: ["Funky Cat"],
  },
  {
    name: "Pagani",
    models: ["Huayra", "Zonda"],
  },
  {
    name: "Peugeot",
    models: [
      "1007",
      "104",
      "106",
      "107",
      "108",
      "2008",
      "204",
      "205",
      "206",
      "207",
      "208",
      "3008",
      "301",
      "304",
      "305",
      "306",
      "307",
      "308",
      "309",
      "4007",
      "4008",
      "404",
      "405",
      "406",
      "407",
      "408",
      "5008",
      "504",
      "505",
      "508",
      "604",
      "605",
      "607",
      "806",
      "Bipper",
      "Bipper Tepee",
      "Boxer",
      "Expert",
      "Expert Tepee",
      "iOn",
      "J5",
      "Partner",
      "Partner Tepee",
      "RCZ",
      "Rifter",
      "TePee",
      "Traveller",
    ],
  },
  {
    name: "Piaggio",
    models: ["APE", "APE TM", "Porter"],
  },
  {
    name: "Plymouth",
    models: ["Prowler"],
  },
  {
    name: "Polestar",
    models: ["1", "2", "3", "4"],
  },
  {
    name: "Pontiac",
    models: [
      "6000",
      "Bonneville",
      "Fiero",
      "Firebird",
      "G6",
      "Grand-Am",
      "Grand Prix",
      "GTO",
      "Montana",
      "Solstice",
      "Sunbird",
      "Sunfire",
      "Targa",
      "Trans Am",
      "Trans Sport",
      "Vibe",
    ],
  },
  {
    name: "Proton",
    models: ["300 Series", "400 Series"],
  },
  {
    name: "Renault",
    models: [
      "Alaskan",
      "Alpine A110",
      "Alpine A310",
      "Alpine V6",
      "Arkana",
      "Austral",
      "Avantime",
      "Captur",
      "Clio",
      "Coupe",
      "Espace",
      "Express",
      "Fluence",
      "Fuego",
      "Grand Espace",
      "Grand Modus",
      "Grand Scenic",
      "Kadjar",
      "Kangoo",
      "Koleos",
      "Laguna",
      "Latitude",
      "Mascott",
      "Master",
      "Megane",
      "Modus",
      "P 1400",
      "R 11",
      "R 14",
      "R 18",
      "R 19",
      "R 20",
      "R 21",
      "R 25",
      "R 30",
      "R 4",
      "R 5",
      "R 6",
      "R 9",
      "Rafale",
      "Rapid",
      "Safrane",
      "Scenic",
      "Spider",
      "Talisman",
      "Trafic",
      "Twingo",
      "Twizy",
      "Vel Satis",
      "Wind",
      "Zoe",
    ],
  },
  {
    name: "Rolls-Royce",
    models: [
      "Corniche",
      "Cullinan",
      "Dawn",
      "Flying Spur",
      "Ghost",
      "Park Ward",
      "Phantom",
      "Silver Cloud",
      "Silver Dawn",
      "Silver Seraph",
      "Silver Shadow",
      "Silver Spirit",
      "Silver Spur",
      "Spectre",
      "Wraith",
    ],
  },
  {
    name: "Rover",
    models: [
      "100",
      "111",
      "114",
      "115",
      "200",
      "213",
      "214",
      "216",
      "218",
      "220",
      "25",
      "400",
      "414",
      "416",
      "418",
      "420",
      "45",
      "600",
      "618",
      "620",
      "623",
      "75",
      "800",
      "820",
      "825",
      "827",
      "City Rover",
      "Metro",
      "Monetgo",
      "SD1",
      "Streetwise",
    ],
  },
  {
    name: "Saab",
    models: [
      "90",
      "900",
      "9000",
      "9-3",
      "9-4X",
      "9-5",
      "9-6",
      "9-7X",
      "96",
      "99",
    ],
  },
  {
    name: "Seat",
    models: [
      "Alhambra",
      "Altea",
      "Arona",
      "Arosa",
      "Ateca",
      "Cordoba",
      "Exeo",
      "Ibiza",
      "Inca",
      "Leon",
      "Malaga",
      "Marbella",
      "Mii",
      "Tarraco",
      "Terra",
      "Toledo",
    ],
  },
  {
    name: "Seres",
    models: ["3", "5"],
  },
  {
    name: "Skoda",
    models: [
      "105",
      "120",
      "130",
      "135",
      "Citigo",
      "Enyaq",
      "Fabia",
      "Favorit",
      "Felicia",
      "Forman",
      "Kamiq",
      "Karoq",
      "Kodiaq",
      "Octavia",
      "Pick-up",
      "Praktik",
      "Rapid",
      "Roomster",
      "Scala",
      "Superb",
      "Yeti",
    ],
  },
  {
    name: "Smart",
    models: ["1", "3", "Crossblade", "ForFour", "ForTwo", "Roadster"],
  },
  {
    name: "Spyker",
    models: [
      "C8",
      "C8 Aileron",
      "C8 Double 12 S",
      "C8 Laviolette SWB",
      "C8 Spyder SWB",
    ],
  },
  {
    name: "Ssangyong",
    models: [
      "Actyon",
      "Family",
      "Korando",
      "Kyron",
      "Musso",
      "Rexton",
      "Rodius",
      "Tivoli",
      "Torres",
      "XLV",
    ],
  },
  {
    name: "Subaru",
    models: [
      "B9 Tribeca",
      "Baja",
      "Brz",
      "Crosstrek",
      "Forester",
      "Impreza",
      "Justy",
      "Legacy",
      "Levorg",
      "Libero",
      "Outback",
      "Solterra",
      "SVX",
      "Trezia",
      "Tribeca",
      "Vivio",
      "WRX STI",
      "XT",
      "XV",
    ],
  },
  {
    name: "Suzuki",
    models: [
      "(SX4) S-Cross",
      "Across",
      "Alto",
      "Baleno",
      "Cappuccino",
      "Carry",
      "Celerio",
      "Grand Vitara",
      "Ignis",
      "iK-2",
      "Jimny",
      "Kizashi",
      "Liana",
      "LJ",
      "SJ Samurai",
      "Splash",
      "Super Carry",
      "Swace",
      "Swift",
      "SX4",
      "Vitara",
      "Wagon R+",
      "X-90",
    ],
  },
  {
    name: "SWM",
    models: ["G01"],
  },
  {
    name: "Talbot",
    models: ["Horizon", "Samba"],
  },
  {
    name: "Tata",
    models: [
      "Indica",
      "Indigo",
      "Nano",
      "Safari",
      "Sumo",
      "Telcoline",
      "Telcosport",
      "Xenon",
    ],
  },
  {
    name: "Tesla",
    models: ["Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  },
  {
    name: "Trabant",
    models: ["601"],
  },
  {
    name: "Triumph",
    models: [
      "Dolomite",
      "Herald",
      "Spitfire",
      "TR3",
      "TR4",
      "TR5",
      "TR6",
      "TR7",
      "TR8",
    ],
  },
  {
    name: "TVR",
    models: ["Chimaera", "Griffith", "Tuscan"],
  },
  {
    name: "VinFast",
    models: ["VF8", "VF9"],
  },
  {
    name: "Wartburg",
    models: ["311", "353"],
  },
  {
    name: "WEY",
    models: ["Coffee01", "Coffee02"],
  },
  {
    name: "Wiesmann",
    models: ["MF25", "MF28", "MF3", "MF30", "MF35", "MF4", "MF5"],
  },
  {
    name: "XEV",
    models: ["YOYO"],
  },
  {
    name: "XPENG",
    models: ["G9", "P7"],
  },
];

export async function seedDatabase() {
  for (const brand of brands) {
    const createdBrand = await db.carBrand.create({
      data: {
        name: brand.name,
        models: {
          create: brand.models.map((model) => ({ name: model })),
        },
      },
    });
    console.log(`Created brand ${createdBrand.name}`);
  }
}

seedDatabase()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
